// This file is autogenerated by templates/_version.h with CMAKE

#pragma once

#define APP_CURRENT_VERSION "${CMAKE_PROJECT_VERSION}"
#define GITHUB_REPO_OWNER "${GITHUB_REPO_OWNER}"
#define GITHUB_REPO_NAME "${GITHUB_REPO_NAME}"